# Generated by Django 2.2.11 on 2020-03-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('ST', 'Shirts And Tops'), ('TEES', 'T-Shirts'), ('SK', 'Skirts'), ('HS', 'Hoodies&Sweatshirts')], max_length=20),
        ),
    ]
