# Generated by Django 2.2.11 on 2020-03-21 12:47

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200321_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to=core.models.get_url),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='category',
            field=models.CharField(choices=[('ST', 'Shirts And Tops'), ('TEES', 'T-Shirts'), ('SK', 'Skirts'), ('HS', 'Hoodies&Sweatshirts')], max_length=20),
        ),
    ]
